//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KetabexApi.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserKey()
        {
            this.UserSession = new HashSet<UserSession>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<bool> Isvalid { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string DeviceId { get; set; }
        public string ApiToken { get; set; }
        public string NotificationToken { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSession { get; set; }
    }
}
